name: docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython --install-option="--no-cython-compile"
      - name: Install
        run: |
          python -m pip install --no-cache-dir -r requirements-dev.txt
      - name: Get branch/tag name
        id: get-branch
        uses: ypicard/get-branch-name-github-action@v1
      - name: Generate docs
        if: ${{ success() }}
        run: |
          invoke docs
          mkdir -p deploy/compas_fab/${{ steps.get-branch.outputs.tag }} && mv -T dist/docs deploy/compas_fab/${{ steps.get-branch.outputs.tag }}/
      - name: Deploy docs
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: gramaziokohler/gramaziokohler.github.io
          target_branch: master
          build_dir: deploy
          keep_history: true
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
